site_name: J16MOTO Documentation

theme:
  name: material
  logo: images/logo.png
  favicon: images/logo.png

  palette:
    scheme: default
    primary: white
    accent: blue

  features:
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight

nav:
  - Getting Started:
      - Introduction: getting_started/introduction.md
      - Getting Started: getting_started/getting_started.md
  - ROS 2 tutorials:
      - Basic Tutorial: ros2_basic_tutorial_autonomous_docking_j16moto.ipynb

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets

plugins:
  - search
  - mkdocs-jupyter

extra_css:
  - stylesheets/extra.css